# Generated by Django 4.2.4 on 2023-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songLibrary', '0002_album_artist_user_playlist_user_playlist_songs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_playlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(through='songLibrary.Artist_Album', to='songLibrary.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(through='songLibrary.Album_Songs', to='songLibrary.song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ManyToManyField(through='songLibrary.Song_Artist', to='songLibrary.song'),
        ),
        migrations.AddField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(through='songLibrary.Song_Genre', to='songLibrary.song'),
        ),
        migrations.AddField(
            model_name='user_playlist',
            name='song',
            field=models.ManyToManyField(through='songLibrary.User_Playlist_Songs', to='songLibrary.song'),
        ),
    ]
