# Generated by Django 4.2.4 on 2023-08-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songLibrary', '0003_remove_user_playlist_user_id_album_artist_album_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song_genre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='song_genre',
            old_name='song_id',
            new_name='song',
        ),
    ]
