# Generated by Django 4.2.4 on 2023-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songLibrary', '0004_rename_genre_id_song_genre_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_playlist',
            old_name='song',
            new_name='songs',
        ),
    ]
